# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eceba1ef1edcb2550db2b441ac09ceca4fbb07793e18448d61a180cfc914be3c915115322b50d69d75cb56249275e3d584c79e384547253f8f669a01864a6a7e

test:
  secret_key_base: 5c59aa81ef4d7d6b98464eb215b1c6697fee61a408bee1eef88f00f2714d2f8ca5df2551a5c9b5f763c64c6ce79fdb013174757e2e2bbbd59aadb62f90723833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
